name: Scan Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  IMAGE_DOCKERHUB: ${{ secrets.DOCKERHUB_USERNAME }}/dotnet9-job-notificacao
  DIR_WEBAPP: './src/WorkerContagem'
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build de imagem
      run: |
        cd ${{ env.DIR_WEBAPP }}
        docker build . -t image-to-scan-test:$GITHUB_RUN_NUMBER --no-cache
    - name: Login no Docker Hub
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PAT }}
    - name: Geração de tag com número do Build e Push no Docker Hub
      run: |
        docker tag ${{ env.IMAGE_DOCKERHUB }}:latest ${{ env.IMAGE_DOCKERHUB }}:$GITHUB_RUN_NUMBER
    - name: Docker Scout
  # You may pin to the exact commit or the version.
  # uses: docker/scout-action@6ac950eb733f8b2811f25c05d97bfb3d181b8026
      uses: docker/scout-action@v1.15.1
      with:
        command: cves
        image: image-to-scan-test:$GITHUB_RUN_NUMBER
        sarif-file: tests.sarif
        exit-code: 2
        only-severities: critical,high
